### ISSUE TITLE
Bug: Click blog throws TypeError

### ISSUE THREAD

**Issue by samuelrey** [cosmicjs/simple-blog#1]
**Steps to reproduce**
- Clone and install dependencies
- `yarn run development`
- Open localhost:3000 in browser
- Click blog component
- TypeError

**Expected**
A single post view is opened with the full text of the selected blog.

**Actual**
Error is thrown.

**Stack trace**
```
TypeError: Cosmic.getObjectsByType is not a function
    at async.series.callback (/home/psycho/simple-blog/app.js:48:14)
    at /home/psycho/simple-blog/node_modules/async/dist/async.js:3866:24
    at replenish (/home/psycho/simple-blog/node_modules/async/dist/async.js:998:17)
    at /home/psycho/simple-blog/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/home/psycho/simple-blog/node_modules/async/dist/async.js:1027:24)
    at /home/psycho/simple-blog/node_modules/async/dist/async.js:1032:16
    at _parallel (/home/psycho/simple-blog/node_modules/async/dist/async.js:3865:5)
    at Object.series (/home/psycho/simple-blog/node_modules/async/dist/async.js:4721:5)
    at app.get (/home/psycho/simple-blog/app.js:46:9)
    at Layer.handle [as handle_request] (/home/psycho/simple-blog/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by tonyspiro** [comment]
I was not able to reproduce this issue @samuelrey.  Are you trying to run an older version?  Make sure the cosmicjs NPM modue is ^2.4.20.

**Comment by samuelrey** [comment]
Found that `yarn` did not install the dependencies by itself. I had to run `npm i` & found that everything worked as expected.
